### ISSUE TITLE
CDI 1.0 and 1.1 compatibility?

### ISSUE THREAD

**Issue by cchacin** [astefanutti/metrics-cdi#6]
TomEE v1.7.2 is a JavaEE 6 server and uses CDI but in a lower version that in this library, is there some possibility of be compatible with JavaEE 6? Which CDI 1.2 features are required for this library?

**Comment by cchacin** [comment]
I saw ```@AroundConstruct``` CDI 1.2 feature, I'm trying to find a workaround with CDI 1.1, but i think is not trivial

**Comment by astefanutti** [comment]
Java EE 6 uses CDI 1.0 (JSR 299) which lacks the following features compared to 1.2 that are leveraged by Metrics CDI:
- `@Priority` annotation for global enablement of interceptors and alternatives (CDI 1.1 feature depending on Java Interceptors Specification 1.2),
- `@AroundConstruct` lifecycle callback for constructors (CDI 1.1 feature depending on Java Interceptors Specification 1.2),
- `@Vetoed` annotation (CDI 1.1 specification),
- `@WithAnnotations` annotation (CDI 1.1 specification),
-  Portable behaviour of `getBeans` method call in `AfterBeanDiscovery` lifecycle callback (CDI 1.2 specification).

So the majority of missing features from CDI 1.0 are available starting CDI 1.1 which means that porting Metrics CDI to CDI 1.1 would be a lot easier than porting it to CDI 1.0.

If CDI 1.0 is still a requirement, that is upgrading the OpenWebBeans dependency in your TomEE setup is not possible (as WildFly can be patched to upgrade Weld):
- lack of `@Priority` can be replaced by explicit enablement in `beans.xml` for each user bean archive,
- lack of `@AroundConstruct` could simply be eluded by not offering instrumentation of constructor calls and not having metrics registered when beans get instantiated, 
- `@Vetoed` and `@WithAnnotations` annotations could be emulated in the extension.

A similar work has been done in [Camel CDI](https://github.com/astefanutti/camel-cdi) to provide support for Java EE 6: https://github.com/astefanutti/camel-cdi/commit/541d6d903ffa108f7261000b44fe7300fe93e81b

That being said, it looks like TomEE is upgrading its OpenWebBeans dependency with CDI 1.2 support so that may be an option to wait until the next TomEE release:
https://git1-us-west.apache.org/repos/asf?p=tomee.git;a=blob;f=pom.xml;h=6e257709c8db1252370e83343056928055e4038e;hb=refs/heads/master#l98

**Comment by astefanutti** [comment]
Let me close this. Feel free to reopen if CDI 1.1 compatibility is still a strong requirement.
